version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/public
      - ./nginx.conf:/etc/nginx/conf.d
    links:
      - php
  php:
    build:
      context: .
    #image: registry.gitlab.com/e-commerce/dte-api-rest:develop
    volumes:
      - ./app:/var/www/public
    tty: true
    # networks:
    #   - erp-brik
  